# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: CaffeineMC/lithium-fabric
          path: work
          ref: 1.18.x/dev
  
      -   name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
              distribution: 'adopt'
              java-version: 17
      -   name: Grant execute permission for gradlew
          run: |
            cd work
            chmod +x gradlew
      -   name: Build with Gradle
          run: |
            cd work
            ./gradlew build

      -   name: Upload build artifacts
          uses: actions/upload-artifact@v1
          with:
              name: build-artifacts
              path: work/build/libs
